/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg04_01_exercise;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pkg04_01_exercise.Menu_funcionario;
import pkg04_01_exercise.Menu_funcionario;

/**
 *
 * @author aluno
 */
public class Layson_Tela_CadastroProduto extends javax.swing.JFrame {

    private PreparedStatement statement;

    /**
     * Creates new form Layson_Tela_CadastroProduto
     */
    public Layson_Tela_CadastroProduto() {
        initComponents();
    }
    
    public void PopularJTable(String sql) {
    try
  {
   Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3307/fashionfoot", "ff_layson", "123456");
   PreparedStatement banco = (PreparedStatement)con.prepareStatement(sql);
   banco.execute(); 
 
   ResultSet resultado = banco.executeQuery(sql);
 
   DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
   model.setNumRows(0);
 
   while(resultado.next())
   {
       model.addRow(new Object[] 
       { 
          //retorna os dados da tabela do BD, cada campo e um coluna.
          //codigo,nome,condicao,tamanho,unidades,categoria,preco,valor_venda,peso,descricao
          resultado.getString("id"),
          resultado.getString("codigo"),
          resultado.getString("nome"),
          resultado.getString("condicao"),
          resultado.getString("tamanho"),
          resultado.getString("unidades"),
          resultado.getString("categoria"),
          resultado.getString("preco"),
          resultado.getString("valor_venda"),
          resultado.getString("peso"),
          resultado.getString("descricao")
       }); 
  } 
   banco.close();
   con.close();
  }
 catch (SQLException ex)
 {
    System.out.println("o erro foi " +ex);
  }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bot_voltar_cadastroProd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cod_produto = new javax.swing.JTextField();
        txt_nome_produto = new javax.swing.JTextField();
        condicao_produto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        unidades_produto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tamanho_produto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        categoria_produto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        preco_produto = new javax.swing.JTextField();
        peso_produto = new javax.swing.JTextField();
        valor_produto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_produto = new javax.swing.JTextArea();
        Bt_Inserir_CadastroDeProduto = new javax.swing.JButton();
        botao_cadastrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_ID_Deletar_CadastroDeProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Bt_Deletar_CadastroDeProduto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Bt_Atualizar_CadastroDeProduto = new javax.swing.JButton();
        txt_ID_Atualizar_CadastroDeProduto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                Select(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(229, 237, 248));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 562));

        jPanel1.setBackground(new java.awt.Color(17, 69, 139));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRO DE PRODUTO");

        Bot_voltar_cadastroProd.setBackground(new java.awt.Color(17, 69, 139));
        Bot_voltar_cadastroProd.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Bot_voltar_cadastroProd.setForeground(new java.awt.Color(255, 255, 255));
        Bot_voltar_cadastroProd.setText("<");
        Bot_voltar_cadastroProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_voltar_cadastroProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bot_voltar_cadastroProd)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bot_voltar_cadastroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(17, 69, 139));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Adicionar foto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Código");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Condição");

        txt_cod_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_produtoActionPerformed(evt);
            }
        });

        txt_nome_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_produtoActionPerformed(evt);
            }
        });

        condicao_produto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        condicao_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não especificado", "Novo", "Usado", "Danificado" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Tamanho");

        unidades_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidades_produtoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Unidades");

        tamanho_produto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tamanho_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não especificado", "Pequeno", "Médio", "Grande" }));
        tamanho_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho_produtoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Categoria");

        categoria_produto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        categoria_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não especificado", "Esportivo", "Casual", "Social" }));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Preço");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Valor de venda");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Peso");

        preco_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_produtoActionPerformed(evt);
            }
        });

        peso_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_produtoActionPerformed(evt);
            }
        });

        valor_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_produtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(204, 204, 204)
                .addComponent(jLabel4)
                .addGap(169, 169, 169))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cod_produto)
                            .addComponent(tamanho_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(preco_produto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nome_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(unidades_produto)
                            .addComponent(valor_produto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(condicao_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoria_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(peso_produto))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel10)
                        .addGap(185, 185, 185))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel7)
                        .addGap(168, 168, 168))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cod_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condicao_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tamanho_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidades_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preco_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel11.setText("Descricão do produto");

        descricao_produto.setColumns(20);
        descricao_produto.setRows(5);
        descricao_produto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(descricao_produto);

        Bt_Inserir_CadastroDeProduto.setBackground(new java.awt.Color(17, 69, 139));
        Bt_Inserir_CadastroDeProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Bt_Inserir_CadastroDeProduto.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Inserir_CadastroDeProduto.setText("Inserir");
        Bt_Inserir_CadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Inserir_CadastroDeProdutoActionPerformed(evt);
            }
        });

        botao_cadastrar.setBackground(new java.awt.Color(17, 69, 139));
        botao_cadastrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botao_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastrar.setText("Export");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_ID_Deletar_CadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_Deletar_CadastroDeProdutoActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        Bt_Deletar_CadastroDeProduto.setBackground(new java.awt.Color(204, 204, 204));
        Bt_Deletar_CadastroDeProduto.setText("Deletar");
        Bt_Deletar_CadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Deletar_CadastroDeProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bt_Deletar_CadastroDeProduto)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ID_Deletar_CadastroDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID_Deletar_CadastroDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_Deletar_CadastroDeProduto)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("ID");

        Bt_Atualizar_CadastroDeProduto.setBackground(new java.awt.Color(17, 69, 139));
        Bt_Atualizar_CadastroDeProduto.setForeground(new java.awt.Color(255, 255, 255));
        Bt_Atualizar_CadastroDeProduto.setText("Atualizar");
        Bt_Atualizar_CadastroDeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Atualizar_CadastroDeProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ID_Atualizar_CadastroDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(Bt_Atualizar_CadastroDeProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID_Atualizar_CadastroDeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_Atualizar_CadastroDeProduto)
                .addGap(4, 4, 4))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Condição", "Tamanho", "Unidades", "Categoria", "Preço", "Valor Venda", "Peso", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clique(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_cadastrar)
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Bt_Inserir_CadastroDeProduto)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Inserir_CadastroDeProduto)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_cadastrar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        try {
            // TODO add your handling code here:
            FileWriter arq = new FileWriter("C:\\Users\\aluno\\Desktop\\CADASTRO.txt");
            PrintWriter gravarArq = new PrintWriter(arq);
            
            gravarArq.printf("|-------------CADASTRO DE PRODUTO------------|");
            gravarArq.printf("\nCodigo: " + txt_cod_produto.getText() + "     |");
            gravarArq.printf("\nNome: " + txt_nome_produto.getText() + "      |");
            gravarArq.printf("\nCondição: " + condicao_produto.getSelectedItem().toString());
            gravarArq.printf("\nTamanho: " + tamanho_produto.getSelectedItem().toString());
            gravarArq.printf("\nUnidade: " + unidades_produto.getText());
            gravarArq.printf("\nCategoria: " + categoria_produto.getSelectedItem().toString());
            gravarArq.printf("\nPreço: " + preco_produto.getText());
            gravarArq.printf("\nValor de venda: " + valor_produto.getText());
            gravarArq.printf("\nPeso: " + peso_produto.getText());
            gravarArq.printf("\n----------------------------------------------");
            gravarArq.printf("\n<<DESCRIÇÃO DO PRODUTO>> " + "\n" + descricao_produto.getText());
            gravarArq.printf("\n----------------------------------------------");
            
            arq.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void valor_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_produtoActionPerformed

    private void peso_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_produtoActionPerformed

    private void preco_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_produtoActionPerformed

    private void tamanho_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanho_produtoActionPerformed

    private void unidades_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidades_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidades_produtoActionPerformed

    private void txt_nome_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_produtoActionPerformed

    private void txt_cod_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_produtoActionPerformed

    private void Bot_voltar_cadastroProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_voltar_cadastroProdActionPerformed
        // TODO add your handling code here:
        Layson_Tela_CadastroProduto.this.dispose();
        Menu_funcionario menuFuncionario = new Menu_funcionario();
        menuFuncionario.setVisible(true);
    }//GEN-LAST:event_Bot_voltar_cadastroProdActionPerformed

    private void Bt_Inserir_CadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Inserir_CadastroDeProdutoActionPerformed
        
        Connection conexao = null;
           
            
            String url = "jdbc:mysql://localhost:3307/fashionfoot";
            String usuario =  "ff_layson";
            String senha = "123456";
        
        try {
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "insert into cadastro_produto (codigo,nome,condicao,tamanho,unidades,categoria,preco,valor_venda,peso,descricao) values (?,?,?,?,?,?,?,?,?,?)";
        
            statement = conexao.prepareStatement(sql);
            statement.setString(1, txt_cod_produto.getText());
            statement.setString(2, txt_nome_produto.getText());
            statement.setString(3, condicao_produto.getSelectedItem().toString());
            statement.setString(4, tamanho_produto.getSelectedItem().toString());
            statement.setString(5, unidades_produto.getText());
            statement.setString(6, categoria_produto.getSelectedItem().toString());
            statement.setString(7, preco_produto.getText());
            statement.setString(8, valor_produto.getText());
            statement.setString(9, peso_produto.getText());
            statement.setString(10, descricao_produto.getText());
            
            int linhasAfetadas = statement.executeUpdate();
            
            if (linhasAfetadas > 0) {
                 JOptionPane.showMessageDialog(rootPane,"Dados inseridos com sucesso!");
                 this.PopularJTable("SELECT * FROM cadastro_produto ORDER BY id");
            } else {
                 JOptionPane.showMessageDialog(rootPane,"Nenhum dado inserido.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
             try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
                } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao fechar conexão: " + e.getMessage());
            }
        }

            
        
    }//GEN-LAST:event_Bt_Inserir_CadastroDeProdutoActionPerformed

    private void Bt_Atualizar_CadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Atualizar_CadastroDeProdutoActionPerformed
       
         Connection conexao = null;
            
            String url = "jdbc:mysql://localhost:3307/fashionfoot";
            String usuario =  "ff_layson";
            String senha = "123456";
        
        try {
 
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "UPDATE cadastro_produto SET codigo = ? , nome = ? , condicao = ? , tamanho = ? , unidades = ? , categoria = ? , preco = ? , valor_venda = ? , peso = ? , descricao = ?  where id = ?";
            
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, txt_cod_produto.getText());
            statement.setString(2, txt_nome_produto.getText());
            statement.setString(3, condicao_produto.getSelectedItem().toString());
            statement.setString(4, tamanho_produto.getSelectedItem().toString());
            statement.setString(5, unidades_produto.getText());
            statement.setString(6, categoria_produto.getSelectedItem().toString());
            statement.setString(7, preco_produto.getText());
            statement.setString(8, valor_produto.getText());
            statement.setString(9, peso_produto.getText());
            statement.setString(10, descricao_produto.getText());
            statement.setString(11, txt_ID_Atualizar_CadastroDeProduto.getText());
            
            int linhasAfetadas = statement.executeUpdate();
            
            if (linhasAfetadas > 0) {
                JOptionPane.showMessageDialog(rootPane,"Dados atualizados com sucesso!");
                this.PopularJTable("SELECT * FROM cadastro_produto ORDER BY id");
            } else {
                JOptionPane.showMessageDialog(rootPane,"Nenhum dado atualizado.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
                   
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao fechar conexão: " + e.getMessage());
            }        
        }
        
    }//GEN-LAST:event_Bt_Atualizar_CadastroDeProdutoActionPerformed

    private void txt_ID_Deletar_CadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_Deletar_CadastroDeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_Deletar_CadastroDeProdutoActionPerformed

    private void Bt_Deletar_CadastroDeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Deletar_CadastroDeProdutoActionPerformed
         
        Connection conexao = null;
            
            String url = "jdbc:mysql://localhost:3307/fashionfoot";
            String usuario =  "ff_layson";
            String senha = "123456";
        
        try {
 
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "DELETE from cadastro_produto where id = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1,txt_ID_Deletar_CadastroDeProduto.getText());
            
             int linhasAfetadas = statement.executeUpdate();
            
            if(linhasAfetadas > 0){
                JOptionPane.showMessageDialog(rootPane,"Dados excluidos com sucesso!");
                this.PopularJTable("SELECT * FROM cadastro_produto ORDER BY id");
            } else {
                JOptionPane.showMessageDialog(rootPane,"Nenhum dado excluido.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (statement != null) {
                    statement.close();
                }
                if (conexao != null) {
                    conexao.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
          
    }//GEN-LAST:event_Bt_Deletar_CadastroDeProdutoActionPerformed

    private void Select(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Select
        // TODO add your handling code here:
         Connection conexao = null;
        PreparedStatement statement = null;
       
        String url = "jdbc:mysql://localhost:3307/fashionfoot";
        String usuario = "ff_layson";
        String senha = "123456";
        
      
        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
           
            this.PopularJTable("SELECT * FROM cadastro_produto ORDER BY ID");
        } catch (SQLException ex) {
            
           // Logger.getLogger(Tela_Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Select

    private void Clique(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clique
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow(); // retorna a linha selecionada pelo usuario
        txt_ID_Atualizar_CadastroDeProduto.setText(jTable1.getValueAt(linha,0).toString());
        txt_cod_produto.setText(jTable1.getValueAt(linha,1).toString());
        txt_nome_produto.setText(jTable1.getValueAt(linha,2).toString());
        unidades_produto.setText(jTable1.getValueAt(linha,5).toString());
        preco_produto.setText(jTable1.getValueAt(linha,7).toString());
        valor_produto.setText(jTable1.getValueAt(linha,8).toString());
        peso_produto.setText(jTable1.getValueAt(linha,9).toString());
        descricao_produto.setText(jTable1.getValueAt(linha, 10).toString());
        
        
    }//GEN-LAST:event_Clique

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layson_Tela_CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layson_Tela_CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot_voltar_cadastroProd;
    private javax.swing.JButton Bt_Atualizar_CadastroDeProduto;
    private javax.swing.JButton Bt_Deletar_CadastroDeProduto;
    private javax.swing.JButton Bt_Inserir_CadastroDeProduto;
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JComboBox<String> categoria_produto;
    private javax.swing.JComboBox<String> condicao_produto;
    private javax.swing.JTextArea descricao_produto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField peso_produto;
    private javax.swing.JTextField preco_produto;
    private javax.swing.JComboBox<String> tamanho_produto;
    private javax.swing.JTextField txt_ID_Atualizar_CadastroDeProduto;
    private javax.swing.JTextField txt_ID_Deletar_CadastroDeProduto;
    private javax.swing.JTextField txt_cod_produto;
    private javax.swing.JTextField txt_nome_produto;
    private javax.swing.JTextField unidades_produto;
    private javax.swing.JTextField valor_produto;
    // End of variables declaration//GEN-END:variables
}
